"""empty message

Revision ID: 521f9cb1ff18
Revises: eefc6bd34828
Create Date: 2017-08-31 10:16:08.598675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '521f9cb1ff18'
down_revision = 'eefc6bd34828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('secret_fruit', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'secret_fruit')
    # ### end Alembic commands ###
